### PR TITLE
Fix Input Watchers

### LINKED ISSUE #481: Unmask only works for original selector
**Issue:**

Calling `unmask` on individual inputs is not persistent. It removes the formatting for a few hundred milliseconds, then restores the mask.

**Example:**

https://jsfiddle.net/o4zzby58/

**Cause:**

The jQuery `selector` attribute is being used incorrectly as an index for a set of intervals. Some jQuery operations like `filter` also clear the selector, which makes it an unsuitable identifier.

 - [src/jquery.mask.js#L458-L459](https://github.com/igorescobar/jQuery-Mask-Plugin/blob/dd4763c/src/jquery.mask.js#L458-L459)
 - [src/jquery.mask.js#L471-L472](https://github.com/igorescobar/jQuery-Mask-Plugin/blob/dd4763c/src/jquery.mask.js#L471-L472)

**Note:**

The mask does not automatically update if the original query has an empty selector, which could also be avoided.

**Solution:**

Apply a class to masked elements and query them in a global interval.

### PR DESCRIPTION
**Pull request by deckar01**
Fixes #481

The `.selector` property was deprecated in jQuery 1.7 and remove in 3.0, because of it's questionable reliability. https://api.jquery.com/selector/

The test that would have caught the breakage in jQuery 3.0 was written out of order, so it was not actually testing the watcher detecting dynamic elements.

Move the watcher functionality to a static interface that requires supplying the selector as a parameter.

**Changes:**

 - Fix the "dynamic element" test
 - Create a static watcher interface
 - Allow grunt to be run from the npm script

### CODE REVIEW

**Comment by igorescobar** [comment]
@deckar01 Ok so in order to support this for jQuery 3+ users the users needs to use
```javascript
$.mask('.date','00/00/0000', /* {} */)
$.unmask('.date')
```
Instead of 
```javascript
$('.date').mask('00/00/0000', /* {} */)
$('.date').unmask('00/00/0000')
```

But basically... this is only necessary if the user wants to watch over dynamically added elements, right?

**Comment by deckar01** [comment]
Correct. The naming could probably be improved to better communicate that the interface is for dynamic behavior.

**Comment by igorescobar** [comment]
@deckar01 what are your thoughts on this:
https://github.com/igorescobar/jQuery-Mask-Plugin/pull/330 

Any ideas on how we could also make this work?

**Comment by igorescobar** [comment]
@deckar01 Also...

Don't would think that instead of creating 2 new interface methods (which is kinda of confunsing) why we don't instead of killing the `watchInputs` we don't just modify it?

```javascript
$('.date').mask('00-00-0000', {watchInputs: '.date'})
```
And then we could use this selector instead of the one inherited from jQuery.

What do you think?

**Comment by deckar01** [comment]
The test provided in #330 currently passes on master, so I'm not sure what the issue is.

> instead of killing the watchInputs we don't just modify it

I thought about this, but the duplication of the selector looked odd to me. I think it violates the object oriented paradigm. Static operations should be static methods of the class, not instance methods.

I don't feel strongly about it though.

**Comment by igorescobar** [comment]
@deckar01 I agree with out but if you look at the pros and cons I think that modifying the `watchInputs` seems to be the one with more pros then cons.

### modifying the `watchInputs` 
#### pros
* don't need to add two more methods to the public interface. (more code, more tests etc).
* less confusing. make it clear what it does.
* the end user maybe will enjoy this more.
* no need to major release.
#### cons
* duplication of the selector (bad object orientation design)

### creating `$.mask`
#### pros
* better object oriented design
#### cons
* more code, more tests etc.
* confusing on what the interface is for.
* I'm not sure how I'm going to introduce this on the documentation.

Can you say more pros points on this?

**Comment by deckar01** [comment]
> modifying the watchInputs: no need to major release.

Currently this library tries to watch the selector by default. Since the fix requires `watchInputs` to be present to enable the watch behavior, then it is not backwards compatible, and would require a major release.

> creating $.mask: confusing on what the interface is for.

This could be fixed with better naming. `$.mask.watch(selector)` `$.mask.unwatch(selector)`

> creating $.mask: more code, more tests etc.

It isn't actually more code. I decoupled 2 functions with complex behavior into 4 functions with simple behavior. It's the difference between `new Job({clean: false}).cookAndClean({clean: false})` and `Job.cook()`. Simple interfaces are easier to use and compose.

Theoretically this change should decrease the number of tests required due to the decreased branch complexity. The code does not currently have full test coverage, so some missing tests still need to be added.

**Comment by igorescobar** [comment]
> Currently this library tries to watch the selector by default. Since the fix requires watchInputs to be present to enable the watch behavior, then it is not backwards compatible, and would require a major release.

I can make it backwards compatible by adding a verification a simple verification on `watchInputs` if true, old behaviour selector = `e.selector`. If its false or undefined do nothing. If its a string use it as a selector.

Lets try not talk about design because this is not my main focus. If it was I should refactor the entire project and have a heavier(kbs) source code. We should focus on what is best in terms of usage (simplicity, source weight etc). I think we can add the same value (which is the goal here) by just changing the way watchInputs property works.

**Comment by deckar01** [comment]
> if true, old behaviour selector = `e.selector`

This still won't work with jQuery 3.0.

> If its false or undefined do nothing.

Currently `watchInputs` defaults to true.

> Lets try not talk about design

I think you mean "Let's not talk about implementation", but breaking the watch behavior out of the main mask functions is a way to improve the API. It's not about refactoring or code style, it is about not making poor API decision for historical consistency and a quick fixes.

**Comment by igorescobar** [comment]
Ok Jared, noted.

I will think about your PR and decide what I'm going to do. Thanks.

Enviado do meu iPhone

**Comment by mstred** [comment]
Hi guys. Have you got any news on this?

**Comment by tilsammans** [comment]
@igorescobar is this still relevant? if not, could you close this issue?

**Comment by michellhornung** [comment]
Same case for me. I'm creating fields dynamically and for the new ones, the loaded mask does not work. I'm cloning fields with the same class as mask is working well for the original field.

`
<input type="text" class="form-control money2">
$('.money2').mask("#.##0,00", {reverse: true});

`
Thoughts?

**Comment by deckar01** [comment]
@tilsammans This is still an issue. Here is the jsfiddle from the issue updated to use the latest (1.14.15) version of this plugin: https://jsfiddle.net/o8vb3gpw/

@michellhornung This plugin is broken for jQuery 3, because it used a deprecated feature that got remove. It has tests for jQuery 3, but they are flawed. This has most recently been reported in #663. Here is the same jsfiddle using the latest (3.3.1) version of jQuery: https://jsfiddle.net/o8vb3gpw/1/

The only real PR that was merged in the last 2 years was reverted. Everything else is docs and commits by the owner directly to master. I am no longer using this plugin otherwise I would fork it and publish a new major version.

**Comment by tilsammans** [comment]
I've been using https://nosir.github.io/cleave.js/ which works very well for me. Thanks for the update, very appreciated.

**Pull request closed without merging**
