### PR TITLE
Fix cursor position

### PR DESCRIPTION
**Pull request by onuradsay**
This PR fixes following issues related cursor position; #510, #509, #514, #516, #529, #538, #544, #546, #551

### CODE REVIEW

**Comment by igorescobar** [comment]
Hey there @onuradsay !

Thanks for you time and effort on this. I will review it as soon as possible okay?

I need to test this PR specially on Android old default Browsers.

**Comment by onuradsay** [comment]
You're welcome. I have tried to test all possible scenarios for adding and deleting characters, but of course it should be also tested on older browsers which are always pain in the neck.

**Comment by igorescobar** [comment]
@onuradsay if you have any android device to test would be great because I don't have it and it makes everything much harder for me.

**Comment by onuradsay** [comment]
I have tested on Android 6.0.1 / Chrome 58.0.3029.83 and it seems to be working fine. If there are any more browsers you want to test specifically, I can test them too.

**Comment by igorescobar** [comment]
This is the little guy who usually creates trouble:
screen shot 2017-05-22 at 15 02 04

**Comment by onuradsay** [comment]
I was able test on android emulator and that little guy has some issues as you expected; whenever a character is added the cursor sets itself before the character. Removing "setTimeout" from  "behaviour" function worked for characters that have no mask digits before them. I think, I have to find a real old device to fix this, because the emulator consumes all of my computer's resources.

**Comment by onuradsay** [comment]
@igorescobar I think, I solved the android default browser issue. In my tests everything worked fine.

**Comment by igorescobar** [comment]
@onuradsay I will take a look into it today okay? So sorry about the delay!

**Comment by igorescobar** [comment]
@onuradsay I believe that your PR added a lot of value. I can see that indeed a lot was fixed. Thanks!

**Comment by onuradsay** [comment]
@igorescobar No problem mate. I hope that all the issues of cursor thing are solved.

**Pull request merged**
