### PR TITLE
Fix to allow mask method to be called on $(this).

### PR DESCRIPTION
**Pull request by papiro**

### CODE REVIEW

**Comment by papiro** [comment]
The Travis build is failing but not due to any change I have made.  Not sure of the fix, but why is the Gruntfile trying to start up a server?  Just wondering...

**Comment by igorescobar** [comment]
Can't accept this change without any unit tests.

**Comment by papiro** [comment]
Added a unit test.  I see that the server is needed to run the test suite, but why is it failing to start up?

**Comment by igorescobar** [comment]
Hey... Im looking into this issue and there is an uncovered scenario here which is the unmask function. The unmask function look into the same watchers and in this case I don't think it will work.

BUT

Think about this a little bit... I don't think that there is a good point on adding watchers to objects... it makes more sense to selectors and not objects (in this case).

Maybe if you show me a jsfiddle with you use case I can figure what exactly are you trying to fix here.

**Comment by papiro** [comment]
Well, the issue is that the selector of $(this) is "".  So, for example, if you have the following block:
    $('.some_input').on('focus', () => {
        $(this).mask('000 000 0000')
    })

It behaves in a way that is unexpected.  We should expect this to work just like calling $('.some_input').mask(...) from within the callback.

**Comment by igorescobar** [comment]
And what exactly doesn't work for you? 

Enviado do meu iPhone

**Comment by papiro** [comment]
The input is not added to the watch-list and so is not masked.  This was the bug I was addressing several months ago.  Has it been fixed through other means perhaps?

**Comment by igorescobar** [comment]
It seems to be working now. But anyway, what I'm trying to say is that the code introduced by your PR try to fix a issue in the watchlist. The watchlist exists to make sure that new items, pragmatically added to your DOM will still be masked... But... This only make sense when we are talking about selector. "this" refers only to one object, there is nothing to be watchable here but when we talk about selectors, yes, a new element with this selector can appear anywhere and that's why that code exists.

If the current master version is working on your use case I see no point on moving forward with this PR.

Enviado do meu iPhone

**Comment by djdenv** [comment]
This appears to still be an issue. The following example does not apply any mask:
`
 $("[mask]").each(function () {
        var m = $(this).attr('mask');
        $(this).mask(m);
    });
`

however changing to a selector based on name does work:
`
$("[mask]").each(function () {
        var m = $(this).attr('mask');
        var name = $(this).attr('name');
        $("[name='"+name+"']").mask(m);
    });
`

**Pull request closed without merging**
