### PR TITLE
Issue 528

### PR DESCRIPTION
**Pull request by jkutianski**
Meteor has his own packager & linter. I change the `package.js` to use the source file.
I changed the package version too for refresh the Atmosphere package.

#528

### CODE REVIEW

**Comment by igorescobar** [comment]
Please to do not change the dist/* files they are auto generated.

**Comment by igorescobar** [comment]
Also, do not change the package.json or the package.js file, they are automatically updated later on the process.

**Comment by jkutianski** [comment]
Sorry @igorescobar I forget about the /dist on my GIT. I change the versions because I don't see the changes reflected on the Atmosphere package. The /src/jquery.mask.js is changed but the /dist/jquery.mask.js is not.

**Comment by igorescobar** [comment]
That's because I didn't release the latest changes on `master` yet :D

**Comment by igorescobar** [comment]
I will do it today!

**Comment by jkutianski** [comment]
Ahhh! OK. I misunderstand the process.

**Comment by igorescobar** [comment]
released!

**Pull request closed without merging**
