### PR TITLE
Maxlength check when used to reverse option.

### PR DESCRIPTION
**Pull request by moacir-selinger**
Hello Igor, as we have talked about the overflow problem in maxlength used as the reverse option, I'm sending a PR for you now. I do not know if it's a good solution and not be applied in the most appropriate place, but I serve as a demonstration for your greater understanding of the problem. If you can take a look and confirm whether or not to implement the suggestion I thank you. Thank you!

### CODE REVIEW

**Comment by igorescobar** [comment]
Build is broken.

**Comment by igorescobar** [comment]
Also, could you write some tests or provide a jsfiddle so I can validate the use case better?

**Comment by HASSED** [comment]
Sorry, I tried to run the tasks of Gruntfile, however, there was a lot of mistakes and I could not solve. How am I doing this work, I can not stay long on, I sent the PR just changed jquery.mask.js file. Follows the Plnkr the case with the alleged problem and solution. Thank you!

Example bug: http://plnkr.co/Yji9m3
Example solution: http://plnkr.co/5kBfBf

**Comment by igorescobar** [comment]
Ok, I'm going to digg into it as soon as possible! Thank you @HASSED

**Comment by igorescobar** [comment]
@HASSED I couldn't open your links so I don't really understood what you're trying to fix... could you write it down or fix those links?

**Comment by HASSED** [comment]
Now running the example links...

Example bug: http://plnkr.co/Yji9m3
Example solution: http://plnkr.co/5kBfBf

**Comment by igorescobar** [comment]
Both links ended up like this:
screen shot 2015-07-08 at 3 50 20 pm

**Comment by HASSED** [comment]
Strange, I tested here and on other computers, opened perfectly. Could you please try again ? If you do not give, try on another computer ? Thank you!

**Comment by igorescobar** [comment]
@moacir-selinger can you tell me if the problem still occurs with latest version?

**Comment by moacir-selinger** [comment]
Good morning @igorescobar, I changed the code in version Plunker he had done and it worked perfectly. Thank you!

**Comment by igorescobar** [comment]
@moacir-selinger YES!

**Pull request closed without merging**
